config/routes.rb
Rails.application.routes.draw do
  resources :students

  resources :attendances

  get 'store/index'

  resources :events

root :to => 'events#index'

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
has_many :students
end

app/models/concerns/current_attendance.rb
module CurrentAttendance
  extend ActiveSupport::Concern

  private

  def set_attendance
    @attendance = Attendance.find(session[:attendance_id])
  rescue ActiveRecord::RecordNotFound
    @attendance = Attendance.create
    session[:attendance_id] = @attendance.id
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
	include ActiveModel::Validations

	has_many :line_items

	validates :category, :module, :date, :supervisor, :time, :duration, presence: true
	validates :module, allow_blank: true, format: {
  with: %r{\A[a-zA-Z]{2}[1-4][0-9]{2}\z},
  message: 'must be a valid module code.'  }


	#validates :category, allow_blank: true, format: {
#  with: %r{\A(lecture)|(tutorial)|(lab)\z}i,
#  message: 'category must be in {lecture, lab, tutorial}.'  }
	
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :event
  belongs_to :attendance
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: [:show, :edit, :update, :destroy]

  # GET /attendances
  # GET /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances
  # POST /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to @attendance, notice: 'Attendance was successfully created.' }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1
  # PATCH/PUT /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance, notice: 'Attendance was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance.destroy
    respond_to do |format|
      format.html { redirect_to attendances_url, notice: 'Attendance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendance_params
      params[:attendance]
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.order( :time).reverse_order
	
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:category, :module, :date, :supervisor, :time, :duration)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	include CurrentAttendance
	before_action :set_attendance, only: [:create]

  before_action :set_student, only: [:show, :edit, :update, :destroy]


  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    event = Event.find(params[:event_id])
		@student = @attendance.students.build(event: event)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student.attendance, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:event_id, :attendance_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/attendances/_form.html.erb
<%= form_for(@attendance) do |f| %>
  <% if @attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
      <% @attendance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing attendance</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<h1>Listing attendances</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <td><%= link_to 'Show', attendance %></td>
        <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
        <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendance', new_attendance_path %>

app/views/attendances/new.html.erb
<h1>New attendance</h1>

<%= render 'form' %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :module %><br>
    <%= f.text_area :module %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :supervisor %><br>
    <%= f.text_field :supervisor %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.time_select :duration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index(2).html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Module</th>
      <th>Date</th>
      <th>Supervisor</th>
      <th>Time</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.category %></td>
        <td><%= event.module %></td>
        <td><%= event.date %></td>
        <td><%= event.supervisor %></td>
        <td><%= event.time %></td>
        <td><%= event.duration %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>Upcoming Events</h1>

<% @events.each do |event| %>
<table class="info_table">
<tr class = "module_row">
	<td class = "first_col"> Module </td>
	<td class = "entry_col"> <%= event.module %> </td>
</tr>
<tr class = "catagory_row">
	<td class = "first_col" id ="a11"> Category </td>
	<td class = "entry_col"> <%= event.category %> </td>
</tr>
<tr class = "date_row">
	<td class = "first_col"> Date</td>
	<td class = "entry_col"> <%= event.date %> </td>
</tr>
<tr class = "time_row">
	<td class = "first_col"> Date</td>
	<td class = "entry_col"> <%= event.time.to_formatted_s(:time) %> </td>
</tr>
<tr class = "duration_row">
	<td class = "first_col"> Duration </td>
	<td class = "entry_col"> <%= event.duration.to_formatted_s(:time) %> </td>
</tr>
<tr>
	<td></td>
	<td><%= button_to 'going', students_path(event_id: event) %> </td>
</tr>



</table>




<% end %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @event.category %>
</p>

<p>
  <strong>Module:</strong>
  <%= @event.module %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Supervisor:</strong>
  <%= @event.supervisor %>
</p>

<p>
  <strong>Time:</strong>
  <%= @event.time %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @event.duration %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Attendance Sheet</title>
  <%=stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="banner">
  <%= @page_title || "Attendance Sheet" %>
</div>
<div id="columns">
  <div id="side">
    <ul>
	<li><a href="http://www....">Home</a></li>
	<li><a href="http://www..../faq">Questions</a></li>
	<li><a href="http://www..../news">News</a></li>
	<li><a href="http://www..../contact">Contact</a></li>
    </ul>
  </div>
  <div id="main">
    <%= yield %>
  </div>
</div>


</body>
</html>

app/views/store/index.html.erb
<h1>Store#index</h1>
<p>Find me in app/views/store/index.html.erb</p>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.text_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :attendance_id %><br>
    <%= f.text_field :attendance_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Attendance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.event %></td>
        <td><%= student.attendance %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @student.event %>
</p>

<p>
  <strong>Attendance:</strong>
  <%= @student.attendance %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>